//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.208
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Phat.Editor.Modules.Editors.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Phat.Editor.Modules.Editors.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        internal static string ArchetypeMenu_Open {
            get {
                return ResourceManager.GetString("ArchetypeMenu_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        internal static string FrameSetMenu_Open {
            get {
                return ResourceManager.GetString("FrameSetMenu_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        internal static string LevelMenu_Open {
            get {
                return ResourceManager.GetString("LevelMenu_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        internal static string PackageMenu_New {
            get {
                return ResourceManager.GetString("PackageMenu_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archetype....
        /// </summary>
        internal static string PackageMenu_New_Archetype {
            get {
                return ResourceManager.GetString("PackageMenu_New_Archetype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frame Set....
        /// </summary>
        internal static string PackageMenu_New_FrameSet {
            get {
                return ResourceManager.GetString("PackageMenu_New_FrameSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level....
        /// </summary>
        internal static string PackageMenu_New_Level {
            get {
                return ResourceManager.GetString("PackageMenu_New_Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sprite....
        /// </summary>
        internal static string PackageMenu_New_Sprite {
            get {
                return ResourceManager.GetString("PackageMenu_New_Sprite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storyboard....
        /// </summary>
        internal static string PackageMenu_New_Storyboard {
            get {
                return ResourceManager.GetString("PackageMenu_New_Storyboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terrain....
        /// </summary>
        internal static string PackageMenu_New_Terrain {
            get {
                return ResourceManager.GetString("PackageMenu_New_Terrain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terrain Tile Definition....
        /// </summary>
        internal static string PackageMenu_New_TerrainTileDefinition {
            get {
                return ResourceManager.GetString("PackageMenu_New_TerrainTileDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Texture....
        /// </summary>
        internal static string PackageMenu_New_Texture {
            get {
                return ResourceManager.GetString("PackageMenu_New_Texture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to World....
        /// </summary>
        internal static string PackageMenu_New_World {
            get {
                return ResourceManager.GetString("PackageMenu_New_World", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        internal static string SpriteMenu_Open {
            get {
                return ResourceManager.GetString("SpriteMenu_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        internal static string StoryboardMenu_Open {
            get {
                return ResourceManager.GetString("StoryboardMenu_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        internal static string TerrainTileDefinitionMenu_Open {
            get {
                return ResourceManager.GetString("TerrainTileDefinitionMenu_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        internal static string Texture2DMenu_Open {
            get {
                return ResourceManager.GetString("Texture2DMenu_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        internal static string WorldMenu_Open {
            get {
                return ResourceManager.GetString("WorldMenu_Open", resourceCulture);
            }
        }
    }
}
